# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  admin_name: admin
  admin_email: lulu.almonddigital@gmail.com
  admin_password: Serenity99
  email_provider_username: <%= ENV["ridecheckout177@gmail.com"] %>
  email_provider_password: <%= ENV["Serenity99"] %>
  domain_name:  https://serene-sierra-72376.herokuapp.com/
  mailchimp_api_key: <%= ENV["092d6f313092f510642a88eb71cb5c57-us14"] %>
  mailchimp_list_id: <%= ENV["Getaride"] %>
  stripe_api_key: <%= ENV["sk_live_vxn9Zz2GUmFFxFtmXpd36WS2"] %>
  stripe_publishable_key: <%= ENV["pk_live_XxNt9MF1sJDAPtRU3x7uVBFW"] %>
  product_title: <%= ENV["PRODUCT_TITLE"] %>
  product_price: <%= ENV["PRODUCT_PRICE"] %>
  secret_key_base: 0ffe80f680e592fb5b2c34596e4da94a430724a2b9f220d1fb2ff0a402559dc57ff6ad5c5e70083b291fe525571409b2ebef75af3b7a518b838ee227ed62cc4a

test:
  domain_name: example.com 
  secret_key_base: 0ffe80f680e592fb5b2c34596e4da94a430724a2b9f220d1fb2ff0a402559dc57ff6ad5c5e70083b291fe525571409b2ebef75af3b7a518b838ee227ed62cc4a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  admin_name: <%= ENV["admin"] %>
  admin_email: <%= ENV["lulu.almonddigital@gmail.com"] %>
  admin_password: <%= ENV["ADMIN_PASSWORD"] %>
  email_provider_username: <%= ENV["ridecheckout177@gmail.com"] %>
  email_provider_password: <%= ENV["Serenity99"] %> 
  domain_name: <%= ENV[" https://serene-sierra-72376.herokuapp.com/"] %>
  mailchimp_api_key: <%= ENV["MAILCHIMP_API_KEY"] %> 
  mailchimp_list_id: <%= ENV["MAILCHIMP_LIST_ID"] %> 
  stripe_api_key: <%= ENV["STRIPE_API_KEY"] %> 
  stripe_publishable_key: <%= ENV["pk_live_XxNt9MF1sJDAPtRU3x7uVBFW"] %> 
  product_title: <%= ENV["Ride"] %> 
  product_price: <%= ENV["$10.00"] %> 
  secret_key_base: <%= ENV["0ffe80f680e592fb5b2c34596e4da94a430724a2b9f220d1fb2ff0a402559dc57ff6ad5c5e70083b291fe525571409b2ebef75af3b7a518b838ee227ed62cc4a"] %>
